import argparse
import shutil
import subprocess
import sys
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Load generated synthetic JSSP instances into jssp_rag_db.py in batches."
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("DT") / "data" / "generated" / "manifest.csv",
        help="Manifest generated by generate_synthetic_jssp.py.",
    )
    parser.add_argument("--batch-size", type=int, default=500)
    parser.add_argument(
        "--batch-index",
        type=int,
        default=None,
        help="0-based batch index. If omitted, all batches are processed sequentially.",
    )
    parser.add_argument("--dt-root", type=Path, default=Path("DT"))
    parser.add_argument("--db-path", type=Path, default=Path("jssp_rag.db"))
    parser.add_argument("--results-dir", type=Path, default=Path("DT") / "results" / "JSSP_RAG")
    parser.add_argument("--sequencing-rules", type=str, default="FIFO")
    parser.add_argument("--dispatching-rules", type=str, default="SPT")
    parser.add_argument("--routing-rule", type=str, default="FIFO")
    parser.add_argument("--teacher-source", choices=["heuristic", "ortools"], default="heuristic")
    parser.add_argument("--teacher-dispatching-rules", type=str, default="SPT")
    parser.add_argument("--teacher-only", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--teacher-mode", choices=["dispatch_rule", "best_run"], default="dispatch_rule")
    parser.add_argument("--teacher-top-k", type=int, default=1)
    parser.add_argument("--ortools-max-time-sec", type=float, default=60.0)
    parser.add_argument("--ortools-require-optimal", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--ortools-spt-improve-ratio", type=float, default=0.0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--significant-digits", type=int, default=10)
    parser.add_argument("--log-chunk-size", type=int, default=4000)
    parser.add_argument("--force-convert", action="store_true")
    parser.add_argument(
        "--copy-only",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Only stage generated CSVs into DT/data/preprocessed, do not call jssp_rag_db.py.",
    )
    parser.add_argument(
        "--python-exe",
        type=Path,
        default=Path(sys.executable),
        help="Python executable used to invoke jssp_rag_db.py.",
    )
    return parser.parse_args()


def load_manifest(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise SystemExit(f"Manifest not found: {path}")
    df = pd.read_csv(path)
    required = {"instance", "file"}
    if not required.issubset(df.columns):
        raise SystemExit(f"Manifest missing required columns {required}: {path}")
    return df


def chunk_rows(df: pd.DataFrame, batch_size: int) -> list[pd.DataFrame]:
    return [df.iloc[i : i + batch_size].copy() for i in range(0, len(df), batch_size)]


def stage_batch_to_preprocessed(batch_df: pd.DataFrame, preprocessed_dir: Path) -> list[str]:
    preprocessed_dir.mkdir(parents=True, exist_ok=True)
    instance_names: list[str] = []
    for row in batch_df.itertuples(index=False):
        instance_name = str(row.instance)
        source_path = Path(str(row.file))
        if not source_path.exists():
            raise SystemExit(f"Generated CSV missing for instance {instance_name}: {source_path}")
        target_path = preprocessed_dir / f"problem_{instance_name}.csv"
        if source_path.resolve() != target_path.resolve():
            shutil.copy2(source_path, target_path)
        instance_names.append(instance_name)
    return instance_names


def build_db_command(args: argparse.Namespace, instance_names: list[str]) -> list[str]:
    cmd = [
        str(args.python_exe),
        "jssp_rag_db.py",
        "--dt-root",
        str(args.dt_root),
        "--db-path",
        str(args.db_path),
        "--results-dir",
        str(args.results_dir),
        "--instances",
        ",".join(instance_names),
        "--sequencing-rules",
        str(args.sequencing_rules),
        "--dispatching-rules",
        str(args.dispatching_rules),
        "--routing-rule",
        str(args.routing_rule),
        "--teacher-source",
        str(args.teacher_source),
        "--teacher-dispatching-rules",
        str(args.teacher_dispatching_rules),
        "--teacher-mode",
        str(args.teacher_mode),
        "--teacher-top-k",
        str(args.teacher_top_k),
        "--ortools-max-time-sec",
        str(args.ortools_max_time_sec),
        "--ortools-spt-improve-ratio",
        str(args.ortools_spt_improve_ratio),
        "--seed",
        str(args.seed),
        "--significant-digits",
        str(args.significant_digits),
        "--log-chunk-size",
        str(args.log_chunk_size),
    ]
    if args.teacher_only:
        cmd.append("--teacher-only")
    if args.ortools_require_optimal:
        cmd.append("--ortools-require-optimal")
    if args.force_convert:
        cmd.append("--force-convert")
    return cmd


def run_batch(args: argparse.Namespace, batch_df: pd.DataFrame, batch_number: int, total_batches: int) -> None:
    preprocessed_dir = args.dt_root / "data" / "preprocessed"
    instance_names = stage_batch_to_preprocessed(batch_df, preprocessed_dir)
    print(f"[BATCH {batch_number}/{total_batches}] staged {len(instance_names)} instances")
    print(f"  first={instance_names[0]} last={instance_names[-1]}")
    if args.copy_only:
        return
    cmd = build_db_command(args, instance_names)
    subprocess.run(cmd, cwd=str(Path(__file__).resolve().parent), check=True)


def main() -> None:
    args = parse_args()
    if args.batch_size <= 0:
        raise SystemExit("--batch-size must be positive.")

    manifest_df = load_manifest(args.manifest)
    batches = chunk_rows(manifest_df, args.batch_size)
    if not batches:
        raise SystemExit("Manifest is empty.")

    if args.batch_index is not None:
        if args.batch_index < 0 or args.batch_index >= len(batches):
            raise SystemExit(f"--batch-index out of range. Valid range: 0..{len(batches)-1}")
        selected = [(args.batch_index + 1, batches[args.batch_index])]
    else:
        selected = [(idx + 1, batch_df) for idx, batch_df in enumerate(batches)]

    total_batches = len(batches)
    for batch_number, batch_df in selected:
        run_batch(args, batch_df, batch_number, total_batches)

    print("Completed generated-batch loading.")


if __name__ == "__main__":
    main()
